apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0a682d01daf8fd105
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  containers: #docker run -d --name-nginx nginx
    - name: nginx
      image: nginx
      volumeMounts: #docker run -v hostpath:containerpath 
        - name: ebs-static
          mountPath: /usr/share/nginx/html #we are mounting data to this path
  volumes:
    - name: ebs-static
      persistentVolumeClaim:
        claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

