apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: expense-ebs
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  label:
    purpose: ebs-dynamic
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: expense-dynamic
          mountPath: /usr/share/nginx/html
  volumes:
    - name: expense-dynamic
      persistentVolumeClaim:
        claimName: expense-dynamic
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30008
