apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-expense
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-037afe97b158088da
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-expense-claim
spec:
  volumeName:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-expense-static
  labels:
    purpose: efs-static
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: efs-expense
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-expense
    persistentVolumeClaim:
      claimName: efs-expense-claim
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007