# apiVersion: v1
# kind: Pod
# metadata: 
#   name: nginx-pod
# spec:
#   containers:
#     - name: nginx
#       image: nginx
#       env:
#         - name: started_on
#           valueFrom:
#             configMapKeyRef:
#              name: nginx-config
#              key: start
#         - name: ended_on
#           valueFrom:
#             configMapKeyRef:
#              name: nginx-config
#              key: end

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        configMapKeyRef:
          name: nginx-config