apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: started_on
          valueFrom:
            configMapKeyRef:
             name: nginx-config
             key: start_date
        - name: end
          valueFrom:
            configMapKeyRef:
             name: nginx-config
             key: end_date