apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret
  labels:
    name: yash
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
       - secretRef:
          name: pod-secret-hm

#aGVsbG8K
#cG90dGkxNDMK

