apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
       - configMapRef:
          name: nginx-config
       - secretRef:
          name: pod-secret-hm

#aGVsbG8K
#cG90dGkxNDMK

