apiVersion: v1
kind: Service
metadata: 
  name: nginx-annotations-service
spec:
  selector:
    practice: "2.5months"
    Project: DevOps
  ports:
    - protocol: TCP
      port: 80
      targetport: 80