apiVersion: v1
kind: Service
metadata: 
  name: nginx-np
type: NodePort
spec:
  selector:
    Project: expense
    env: dev
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80