apiVersion: v1
kind: Service
metadata: 
  name: nginx-np
type: NodePort
spec:
  selector:
    practice: "2.5months"
    Project: DevOps
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80