apiVersion: v1
kind: Service
metadata: 
  name: nginx-np
type: NodePort
spec:
  selectors:
    practice: "2.5months"
    Project: DevOps
  ports:
    - protocol: TCP
      port: 80
      targetport: 80