apiVersion: v1
kind: Pod
namespace: expense
metadata:
  name: multi-containers
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep" , "890"]